### PR TITLE
Update test.txt

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins alexec@users.noreply.github.com

### CODE REVIEW

**Comment by alexec** [comment]
hmmm.  not possible to sign DCO unless you have checkout the code :(

**Comment by edlee2121** [comment]
You mean from the web gui?

**Comment by alexec** [comment]
Correct. I don't think it is really an issue though.

**Comment by edlee2121** [comment]
Actually, you can, but you either need to make your github email not private or manually include the following sign-off in the comment:
Signed-off-by: github-name <github-handle@users.noreply.github.com>

**Comment by alexec** [comment]
Signed-off-by: Alex Collins alexec@users.noreply.github.com

**Pull request closed without merging**
